/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as krnlSol from "./KRNL.sol";
export type { krnlSol };
export type { CustomOpinionMaker } from "./CustomOpinionMaker";
export type { CustomTokenAuthority } from "./CustomTokenAuthority";
export type { KrnlRegistered } from "./KrnlRegistered";
