/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as krnlSol from "./KRNL.sol";
export { CustomOpinionMaker__factory } from "./CustomOpinionMaker__factory";
export { CustomTokenAuthority__factory } from "./CustomTokenAuthority__factory";
export { KrnlRegistered__factory } from "./KrnlRegistered__factory";
